name: CI

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: ./docker-build.sh

    - name: Run Docker Container
      run: ./docker-run.sh
